// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/solutions": {
    params: {};
  };
  "/careers": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/solutions" | "/careers" | "/*";
  };
  "components/Layout.tsx": {
    id: "components/Layout";
    page: "/" | "/about" | "/solutions" | "/careers" | "/*";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/About.tsx": {
    id: "pages/About";
    page: "/about";
  };
  "pages/Solutions.tsx": {
    id: "pages/Solutions";
    page: "/solutions";
  };
  "pages/Careers.tsx": {
    id: "pages/Careers";
    page: "/careers";
  };
  "pages/NotFoundRedirect.tsx": {
    id: "not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/Layout": typeof import("./app/components/Layout.tsx");
  "pages/Home": typeof import("./app/pages/Home.tsx");
  "pages/About": typeof import("./app/pages/About.tsx");
  "pages/Solutions": typeof import("./app/pages/Solutions.tsx");
  "pages/Careers": typeof import("./app/pages/Careers.tsx");
  "not-found": typeof import("./app/pages/NotFoundRedirect.tsx");
};